#include "commander.h"
#include "commander_modules.h"   // generated by cmdr — run `cmdr module`
#include "secrets.h"

extern "C" CommanderConfig commander_config() {
    CommanderConfig cfg;
    cfg.wifi_ssid     = WIFI_SSID;
    cfg.wifi_password = WIFI_PASSWORD;
    cfg.hostname      = "cmdr-oi-bridge";
    cfg.uart_baud     = 115200;
    cfg.uart_greeting = "cmdr-oi-bridge";
    return cfg;
}

extern "C" void commander_setup(CommandRegistry &reg) {
    commander_register_modules(reg);
}
